/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.qw99.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class App {
  TextPlayer player1;
  TextPlayer player2;
  
  public App(TextPlayer p1, TextPlayer p2) {
    this.player1 = p1;
    this.player2 = p2;
  }

  public void doPlacementPhase() throws IOException{
    player1.doPlacementPhase();
    player2.doPlacementPhase();
  }

  public void doAttackingPhase() throws IOException{
    while(true){
      if(player1.theBoard.isLose() == false){
        player1.playOneTurn(player2.theBoard, player2.view, player2.name);
      }
      else{
        player2.out.println(player2.name + "wins!");
        break;
      }
      if(player2.theBoard.isLose() == false){
        player2.playOneTurn(player1.theBoard, player1.view, player1.name);
      }
      else{
        player1.out.println(player1.name + " wins!");
        break;
      }
    }
    System.exit(0);
  }

  public void doAllPhase() throws IOException{
    while(true){
       if(player1.theBoard.isLose() == false){
        player1.doAll(player2.theBoard, player2.view, player2.name);
      }
      else{
        player2.out.println(player2.name + "wins!");
        break;
      }
      if(player2.theBoard.isLose() == false){
        player2.doAll(player1.theBoard, player1.view, player1.name);
      }
      else{
        player1.out.println(player1.name + " wins!");
        break;
      }
    }
    System.exit(0);
  }

  public static void main(String[] args) throws IOException{
    Board<Character> b1 = new BattleShipBoard<Character>(10, 20, 'X');
    Board<Character> b2 = new BattleShipBoard<Character>(10, 20, 'X');
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    V1ShipFactory factory = new V1ShipFactory();
    TextPlayer player1 = new TextPlayer("A", b1, input, System.out, factory);
    TextPlayer player2 = new TextPlayer("B", b2, input, System.out, factory);
    App app = new App(player1, player2);
    app.doPlacementPhase();
    app.doAllPhase();
  }

  
}












